export enum UserTokenType {
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_RESET_KEY = 'PASSWORD_RESET_KEY',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  API_KEY = 'API_KEY',
  TWO_FACTOR_BACKUP = 'TWO_FACTOR_BACKUP',
}
