CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE "users"
ADD COLUMN "current_lat" DOUBLE PRECISION,
ADD COLUMN "current_lng" DOUBLE PRECISION,
ADD COLUMN "location_updated_at" TIMESTAMPTZ(3);

ALTER TABLE "trainer_profiles"
ADD COLUMN "base_location_lat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "base_location_lng" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "live_location_lat" DOUBLE PRECISION,
ADD COLUMN "live_location_lng" DOUBLE PRECISION,
ADD COLUMN "is_online" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "last_seen" TIMESTAMPTZ(3);
